[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "r-provider"
update_changelog_on_bump = true
changelog_file = "NEWS.md"

[tool.commitizen.extras]
project = "stylehaven"
