---
title: "StyleHaven Makeover"
output:
  xaringan::moon_reader:
    nature:
      ratio: 16:9
      countIncrementalSlides: false
vignette: >
  %\VignetteIndexEntry{makeover}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message=FALSE, warning=TRUE, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.showtext = TRUE,
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	comment = "#>",
	dpi = 150,
	out.width = "100%",
	fig.width = 6
)
```

This is a quick behind-the-scenes look at some examples of how & why we might think about building plots with these tools. `stylehaven` helps with making charts more standardized with clean fonts, harmonious color palettes, and labels that help create legible visualizations.

```{r libs, message=FALSE}
library(stylehaven)
library(ggplot2, verbose = FALSE)
library(dplyr, verbose = FALSE)
library(showtext)
library(flipbookr)

showtext_auto()
showtext_opts(dpi = 150)
```

---

```{r style}
font_add_weights("Barlow Semi Condensed", semibold = 500)

base_col <- "#5e3da7"
palx_colors <- palx(base_col, n_shades = 5, plot = TRUE)
qual_pal <- palx_colors$shade03
# use with offset labels to make nearly-white labels inside bars, dark gray labels outside
tf_pal <- c("TRUE" = palx_colors[["shade02"]][["gray"]], "FALSE" = palx_colors[["shade05"]][["gray"]])

theme_bar <- function(x, ygrid = FALSE, ...) {
  camiller::theme_din(base_family = "Barlow Semi Condensed", ygrid = ygrid) +
    theme(plot.caption.position = "plot", 
          plot.subtitle = element_text(size = rel(0.95)),
          strip.text = element_text(family = "Barlow Semi Condensed Semibold", face = "plain"))
}
theme_set(theme_bar())
update_geom_defaults("col", list(fill = base_col))
update_geom_defaults("text", list(size = 3.5, fontface = "bold", family = "Barlow Semi Condensed", color = tf_pal[["FALSE"]]))
```

---

```{r rent1}
rent_plot <- rent_x_income %>%
  filter(bedrooms == "2br",
         name %in% c("New Haven", cwi::regions$`New Haven Inner Ring`)) %>%
  mutate(name = forcats::as_factor(name) %>%
           forcats::fct_reorder(income, .desc = TRUE)) %>%
  tidyr::pivot_longer(c(income, income_needed), names_to = "measure") %>%
  mutate(measure = forcats::as_factor(measure) %>%
           forcats::fct_recode(avg_income = "income") %>%
           forcats::fct_relabel(camiller::clean_titles)) %>%
  ggplot(aes(x = name, y = value, fill = measure)) +
  geom_col(width = 0.8, position = position_dodge2()) +
  theme_bar(ygrid = TRUE) +
  labs(x = NULL, y = "Income ($)", fill = NULL,
       title = "A two-bedroom apartment is far from affordable for the average renter household.",
       subtitle = "Median renter household income vs. income needed to afford median rent for 2br housing\nbased on HUD affordability guidelines, 2019")

rent_plot
```

```{r}

```

